//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DenetimKayitlari
    {
        public int DenetimID { get; set; }
        public Nullable<int> KullaniciNo { get; set; }
        public string Eylem { get; set; }
        public System.DateTime ZamanDamgasi { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
